networks:
  local:

services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: nginx.Dockerfile
    image: "fst-nginx"
    container_name: "fst-nginx"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./php:/app:ro
    ports:
      - "8080:8080"
    networks:
      - local
    depends_on:
      - app

  app: &app
    build:
      context: .
      dockerfile: ./docker/app/app.Dockerfile
      args:
        HOST_UID: 1000
        HOST_GID: 1000
    image: "fst-app"
    container_name: "fst-app"
    user: "1000"
    tty: true
    networks:
      - local
    volumes:
      - ./php:/app:rw
      - ./docker/app/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/app/php/zz-option.conf:/usr/local/etc/php-fpm.d/zz-option.conf
      - ./docker/app/php/99-zz.ini:/usr/local/etc/php/conf.d/99-zz.ini
    depends_on:
      - redis
      - postgres

  buggregator:
    image: butschster/buggregator:1
    container_name: "fst-buggregator"
    ports:
      - "8082:8000"
    networks:
      - local

  client:
    image: node:25-alpine3.22
    container_name: "fst-client"
    user: "1000"
    tty: true
    ports:
      - "3000:3000"
    networks:
      - local
    volumes:
      - ./client:/app:rw

  redis:
    image: redis:7.4-alpine
    container_name: "fst-redis"
    networks:
      - local
    volumes:
      - redis_data:/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 2s
      timeout: 5s

  postgres:
    image: "postgres:14.19-alpine3.21"
    container_name: "fst-postgres"
    environment:
      POSTGRES_DB: fst
      POSTGRES_USER: fst
      POSTGRES_PASSWORD: fst
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata:rw
    networks:
      - local
    healthcheck: # Healthcheck docs: <https://docs.docker.com/engine/reference/builder/#healthcheck>
      test: [ "CMD-SHELL", "pg_isready -U ruport_career" ]
      interval: 2s
      timeout: 5s

volumes:
  redis_data:
  pg_data: